// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "workflow-approval/package/workflow_step/domain"

	mock "github.com/stretchr/testify/mock"
)

// WorkflowStepService is an autogenerated mock type for the WorkflowStepService type
type WorkflowStepService struct {
	mock.Mock
}

type WorkflowStepService_Expecter struct {
	mock *mock.Mock
}

func (_m *WorkflowStepService) EXPECT() *WorkflowStepService_Expecter {
	return &WorkflowStepService_Expecter{mock: &_m.Mock}
}

// CreateStep provides a mock function with given fields: ctx, workflowID, level, actorID, conditions
func (_m *WorkflowStepService) CreateStep(ctx context.Context, workflowID string, level int, actorID string, conditions domain.StepConditions) (*domain.WorkflowStep, error) {
	ret := _m.Called(ctx, workflowID, level, actorID, conditions)

	var r0 *domain.WorkflowStep
	if rf, ok := ret.Get(0).(func(context.Context, string, int, string, domain.StepConditions) *domain.WorkflowStep); ok {
		r0 = rf(ctx, workflowID, level, actorID, conditions)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.WorkflowStep)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, int, string, domain.StepConditions) error); ok {
		r1 = rf(ctx, workflowID, level, actorID, conditions)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WorkflowStepService_CreateStep_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateStep'
type WorkflowStepService_CreateStep_Call struct {
	*mock.Call
}

// CreateStep is a helper method to define mock.On call
//  - ctx context.Context
//  - workflowID string
//  - level int
//  - actorID string
//  - conditions domain.StepConditions
func (_e *WorkflowStepService_Expecter) CreateStep(ctx interface{}, workflowID interface{}, level interface{}, actorID interface{}, conditions interface{}) *WorkflowStepService_CreateStep_Call {
	return &WorkflowStepService_CreateStep_Call{Call: _e.mock.On("CreateStep", ctx, workflowID, level, actorID, conditions)}
}

func (_c *WorkflowStepService_CreateStep_Call) Run(run func(ctx context.Context, workflowID string, level int, actorID string, conditions domain.StepConditions)) *WorkflowStepService_CreateStep_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].(string), args[4].(domain.StepConditions))
	})
	return _c
}

func (_c *WorkflowStepService_CreateStep_Call) Return(_a0 *domain.WorkflowStep, _a1 error) *WorkflowStepService_CreateStep_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// DeleteStep provides a mock function with given fields: ctx, id
func (_m *WorkflowStepService) DeleteStep(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WorkflowStepService_DeleteStep_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteStep'
type WorkflowStepService_DeleteStep_Call struct {
	*mock.Call
}

// DeleteStep is a helper method to define mock.On call
//  - ctx context.Context
//  - id string
func (_e *WorkflowStepService_Expecter) DeleteStep(ctx interface{}, id interface{}) *WorkflowStepService_DeleteStep_Call {
	return &WorkflowStepService_DeleteStep_Call{Call: _e.mock.On("DeleteStep", ctx, id)}
}

func (_c *WorkflowStepService_DeleteStep_Call) Run(run func(ctx context.Context, id string)) *WorkflowStepService_DeleteStep_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *WorkflowStepService_DeleteStep_Call) Return(_a0 error) *WorkflowStepService_DeleteStep_Call {
	_c.Call.Return(_a0)
	return _c
}

// GetStepByID provides a mock function with given fields: ctx, id
func (_m *WorkflowStepService) GetStepByID(ctx context.Context, id string) (*domain.WorkflowStep, error) {
	ret := _m.Called(ctx, id)

	var r0 *domain.WorkflowStep
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.WorkflowStep); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.WorkflowStep)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WorkflowStepService_GetStepByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStepByID'
type WorkflowStepService_GetStepByID_Call struct {
	*mock.Call
}

// GetStepByID is a helper method to define mock.On call
//  - ctx context.Context
//  - id string
func (_e *WorkflowStepService_Expecter) GetStepByID(ctx interface{}, id interface{}) *WorkflowStepService_GetStepByID_Call {
	return &WorkflowStepService_GetStepByID_Call{Call: _e.mock.On("GetStepByID", ctx, id)}
}

func (_c *WorkflowStepService_GetStepByID_Call) Run(run func(ctx context.Context, id string)) *WorkflowStepService_GetStepByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *WorkflowStepService_GetStepByID_Call) Return(_a0 *domain.WorkflowStep, _a1 error) *WorkflowStepService_GetStepByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// GetSteps provides a mock function with given fields: ctx, workflowID
func (_m *WorkflowStepService) GetSteps(ctx context.Context, workflowID string) ([]*domain.WorkflowStep, error) {
	ret := _m.Called(ctx, workflowID)

	var r0 []*domain.WorkflowStep
	if rf, ok := ret.Get(0).(func(context.Context, string) []*domain.WorkflowStep); ok {
		r0 = rf(ctx, workflowID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.WorkflowStep)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, workflowID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WorkflowStepService_GetSteps_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSteps'
type WorkflowStepService_GetSteps_Call struct {
	*mock.Call
}

// GetSteps is a helper method to define mock.On call
//  - ctx context.Context
//  - workflowID string
func (_e *WorkflowStepService_Expecter) GetSteps(ctx interface{}, workflowID interface{}) *WorkflowStepService_GetSteps_Call {
	return &WorkflowStepService_GetSteps_Call{Call: _e.mock.On("GetSteps", ctx, workflowID)}
}

func (_c *WorkflowStepService_GetSteps_Call) Run(run func(ctx context.Context, workflowID string)) *WorkflowStepService_GetSteps_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *WorkflowStepService_GetSteps_Call) Return(_a0 []*domain.WorkflowStep, _a1 error) *WorkflowStepService_GetSteps_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// UpdateStep provides a mock function with given fields: ctx, id, level, actorID, conditions
func (_m *WorkflowStepService) UpdateStep(ctx context.Context, id string, level int, actorID string, conditions domain.StepConditions) (*domain.WorkflowStep, error) {
	ret := _m.Called(ctx, id, level, actorID, conditions)

	var r0 *domain.WorkflowStep
	if rf, ok := ret.Get(0).(func(context.Context, string, int, string, domain.StepConditions) *domain.WorkflowStep); ok {
		r0 = rf(ctx, id, level, actorID, conditions)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.WorkflowStep)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, int, string, domain.StepConditions) error); ok {
		r1 = rf(ctx, id, level, actorID, conditions)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WorkflowStepService_UpdateStep_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStep'
type WorkflowStepService_UpdateStep_Call struct {
	*mock.Call
}

// UpdateStep is a helper method to define mock.On call
//  - ctx context.Context
//  - id string
//  - level int
//  - actorID string
//  - conditions domain.StepConditions
func (_e *WorkflowStepService_Expecter) UpdateStep(ctx interface{}, id interface{}, level interface{}, actorID interface{}, conditions interface{}) *WorkflowStepService_UpdateStep_Call {
	return &WorkflowStepService_UpdateStep_Call{Call: _e.mock.On("UpdateStep", ctx, id, level, actorID, conditions)}
}

func (_c *WorkflowStepService_UpdateStep_Call) Run(run func(ctx context.Context, id string, level int, actorID string, conditions domain.StepConditions)) *WorkflowStepService_UpdateStep_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].(string), args[4].(domain.StepConditions))
	})
	return _c
}

func (_c *WorkflowStepService_UpdateStep_Call) Return(_a0 *domain.WorkflowStep, _a1 error) *WorkflowStepService_UpdateStep_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

type mockConstructorTestingTNewWorkflowStepService interface {
	mock.TestingT
	Cleanup(func())
}

// NewWorkflowStepService creates a new instance of WorkflowStepService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewWorkflowStepService(t mockConstructorTestingTNewWorkflowStepService) *WorkflowStepService {
	mock := &WorkflowStepService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
