// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "workflow-approval/package/workflow_step/domain"

	mock "github.com/stretchr/testify/mock"
)

// WorkflowStepRepository is an autogenerated mock type for the WorkflowStepRepository type
type WorkflowStepRepository struct {
	mock.Mock
}

type WorkflowStepRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *WorkflowStepRepository) EXPECT() *WorkflowStepRepository_Expecter {
	return &WorkflowStepRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, step
func (_m *WorkflowStepRepository) Create(ctx context.Context, step *domain.WorkflowStep) error {
	ret := _m.Called(ctx, step)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.WorkflowStep) error); ok {
		r0 = rf(ctx, step)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WorkflowStepRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type WorkflowStepRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//  - ctx context.Context
//  - step *domain.WorkflowStep
func (_e *WorkflowStepRepository_Expecter) Create(ctx interface{}, step interface{}) *WorkflowStepRepository_Create_Call {
	return &WorkflowStepRepository_Create_Call{Call: _e.mock.On("Create", ctx, step)}
}

func (_c *WorkflowStepRepository_Create_Call) Run(run func(ctx context.Context, step *domain.WorkflowStep)) *WorkflowStepRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.WorkflowStep))
	})
	return _c
}

func (_c *WorkflowStepRepository_Create_Call) Return(_a0 error) *WorkflowStepRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *WorkflowStepRepository) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WorkflowStepRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type WorkflowStepRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//  - ctx context.Context
//  - id string
func (_e *WorkflowStepRepository_Expecter) Delete(ctx interface{}, id interface{}) *WorkflowStepRepository_Delete_Call {
	return &WorkflowStepRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *WorkflowStepRepository_Delete_Call) Run(run func(ctx context.Context, id string)) *WorkflowStepRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *WorkflowStepRepository_Delete_Call) Return(_a0 error) *WorkflowStepRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *WorkflowStepRepository) GetByID(ctx context.Context, id string) (*domain.WorkflowStep, error) {
	ret := _m.Called(ctx, id)

	var r0 *domain.WorkflowStep
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.WorkflowStep); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.WorkflowStep)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WorkflowStepRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type WorkflowStepRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//  - ctx context.Context
//  - id string
func (_e *WorkflowStepRepository_Expecter) GetByID(ctx interface{}, id interface{}) *WorkflowStepRepository_GetByID_Call {
	return &WorkflowStepRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *WorkflowStepRepository_GetByID_Call) Run(run func(ctx context.Context, id string)) *WorkflowStepRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *WorkflowStepRepository_GetByID_Call) Return(_a0 *domain.WorkflowStep, _a1 error) *WorkflowStepRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// GetByWorkflowAndLevel provides a mock function with given fields: ctx, workflowID, level
func (_m *WorkflowStepRepository) GetByWorkflowAndLevel(ctx context.Context, workflowID string, level int) (*domain.WorkflowStep, error) {
	ret := _m.Called(ctx, workflowID, level)

	var r0 *domain.WorkflowStep
	if rf, ok := ret.Get(0).(func(context.Context, string, int) *domain.WorkflowStep); ok {
		r0 = rf(ctx, workflowID, level)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.WorkflowStep)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = rf(ctx, workflowID, level)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WorkflowStepRepository_GetByWorkflowAndLevel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByWorkflowAndLevel'
type WorkflowStepRepository_GetByWorkflowAndLevel_Call struct {
	*mock.Call
}

// GetByWorkflowAndLevel is a helper method to define mock.On call
//  - ctx context.Context
//  - workflowID string
//  - level int
func (_e *WorkflowStepRepository_Expecter) GetByWorkflowAndLevel(ctx interface{}, workflowID interface{}, level interface{}) *WorkflowStepRepository_GetByWorkflowAndLevel_Call {
	return &WorkflowStepRepository_GetByWorkflowAndLevel_Call{Call: _e.mock.On("GetByWorkflowAndLevel", ctx, workflowID, level)}
}

func (_c *WorkflowStepRepository_GetByWorkflowAndLevel_Call) Run(run func(ctx context.Context, workflowID string, level int)) *WorkflowStepRepository_GetByWorkflowAndLevel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int))
	})
	return _c
}

func (_c *WorkflowStepRepository_GetByWorkflowAndLevel_Call) Return(_a0 *domain.WorkflowStep, _a1 error) *WorkflowStepRepository_GetByWorkflowAndLevel_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// GetByWorkflowID provides a mock function with given fields: ctx, workflowID
func (_m *WorkflowStepRepository) GetByWorkflowID(ctx context.Context, workflowID string) ([]*domain.WorkflowStep, error) {
	ret := _m.Called(ctx, workflowID)

	var r0 []*domain.WorkflowStep
	if rf, ok := ret.Get(0).(func(context.Context, string) []*domain.WorkflowStep); ok {
		r0 = rf(ctx, workflowID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.WorkflowStep)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, workflowID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WorkflowStepRepository_GetByWorkflowID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByWorkflowID'
type WorkflowStepRepository_GetByWorkflowID_Call struct {
	*mock.Call
}

// GetByWorkflowID is a helper method to define mock.On call
//  - ctx context.Context
//  - workflowID string
func (_e *WorkflowStepRepository_Expecter) GetByWorkflowID(ctx interface{}, workflowID interface{}) *WorkflowStepRepository_GetByWorkflowID_Call {
	return &WorkflowStepRepository_GetByWorkflowID_Call{Call: _e.mock.On("GetByWorkflowID", ctx, workflowID)}
}

func (_c *WorkflowStepRepository_GetByWorkflowID_Call) Run(run func(ctx context.Context, workflowID string)) *WorkflowStepRepository_GetByWorkflowID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *WorkflowStepRepository_GetByWorkflowID_Call) Return(_a0 []*domain.WorkflowStep, _a1 error) *WorkflowStepRepository_GetByWorkflowID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// Update provides a mock function with given fields: ctx, step
func (_m *WorkflowStepRepository) Update(ctx context.Context, step *domain.WorkflowStep) error {
	ret := _m.Called(ctx, step)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.WorkflowStep) error); ok {
		r0 = rf(ctx, step)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WorkflowStepRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type WorkflowStepRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//  - ctx context.Context
//  - step *domain.WorkflowStep
func (_e *WorkflowStepRepository_Expecter) Update(ctx interface{}, step interface{}) *WorkflowStepRepository_Update_Call {
	return &WorkflowStepRepository_Update_Call{Call: _e.mock.On("Update", ctx, step)}
}

func (_c *WorkflowStepRepository_Update_Call) Run(run func(ctx context.Context, step *domain.WorkflowStep)) *WorkflowStepRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.WorkflowStep))
	})
	return _c
}

func (_c *WorkflowStepRepository_Update_Call) Return(_a0 error) *WorkflowStepRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

type mockConstructorTestingTNewWorkflowStepRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewWorkflowStepRepository creates a new instance of WorkflowStepRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewWorkflowStepRepository(t mockConstructorTestingTNewWorkflowStepRepository) *WorkflowStepRepository {
	mock := &WorkflowStepRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
