// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "workflow-approval/package/workflow/domain"

	mock "github.com/stretchr/testify/mock"
)

// WorkflowService is an autogenerated mock type for the WorkflowService type
type WorkflowService struct {
	mock.Mock
}

type WorkflowService_Expecter struct {
	mock *mock.Mock
}

func (_m *WorkflowService) EXPECT() *WorkflowService_Expecter {
	return &WorkflowService_Expecter{mock: &_m.Mock}
}

// CreateWorkflow provides a mock function with given fields: ctx, name
func (_m *WorkflowService) CreateWorkflow(ctx context.Context, name string) (*domain.Workflow, error) {
	ret := _m.Called(ctx, name)

	var r0 *domain.Workflow
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Workflow); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Workflow)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WorkflowService_CreateWorkflow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateWorkflow'
type WorkflowService_CreateWorkflow_Call struct {
	*mock.Call
}

// CreateWorkflow is a helper method to define mock.On call
//  - ctx context.Context
//  - name string
func (_e *WorkflowService_Expecter) CreateWorkflow(ctx interface{}, name interface{}) *WorkflowService_CreateWorkflow_Call {
	return &WorkflowService_CreateWorkflow_Call{Call: _e.mock.On("CreateWorkflow", ctx, name)}
}

func (_c *WorkflowService_CreateWorkflow_Call) Run(run func(ctx context.Context, name string)) *WorkflowService_CreateWorkflow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *WorkflowService_CreateWorkflow_Call) Return(_a0 *domain.Workflow, _a1 error) *WorkflowService_CreateWorkflow_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// DeleteWorkflow provides a mock function with given fields: ctx, id
func (_m *WorkflowService) DeleteWorkflow(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WorkflowService_DeleteWorkflow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteWorkflow'
type WorkflowService_DeleteWorkflow_Call struct {
	*mock.Call
}

// DeleteWorkflow is a helper method to define mock.On call
//  - ctx context.Context
//  - id string
func (_e *WorkflowService_Expecter) DeleteWorkflow(ctx interface{}, id interface{}) *WorkflowService_DeleteWorkflow_Call {
	return &WorkflowService_DeleteWorkflow_Call{Call: _e.mock.On("DeleteWorkflow", ctx, id)}
}

func (_c *WorkflowService_DeleteWorkflow_Call) Run(run func(ctx context.Context, id string)) *WorkflowService_DeleteWorkflow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *WorkflowService_DeleteWorkflow_Call) Return(_a0 error) *WorkflowService_DeleteWorkflow_Call {
	_c.Call.Return(_a0)
	return _c
}

// GetWorkflow provides a mock function with given fields: ctx, id
func (_m *WorkflowService) GetWorkflow(ctx context.Context, id string) (*domain.Workflow, error) {
	ret := _m.Called(ctx, id)

	var r0 *domain.Workflow
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Workflow); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Workflow)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WorkflowService_GetWorkflow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWorkflow'
type WorkflowService_GetWorkflow_Call struct {
	*mock.Call
}

// GetWorkflow is a helper method to define mock.On call
//  - ctx context.Context
//  - id string
func (_e *WorkflowService_Expecter) GetWorkflow(ctx interface{}, id interface{}) *WorkflowService_GetWorkflow_Call {
	return &WorkflowService_GetWorkflow_Call{Call: _e.mock.On("GetWorkflow", ctx, id)}
}

func (_c *WorkflowService_GetWorkflow_Call) Run(run func(ctx context.Context, id string)) *WorkflowService_GetWorkflow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *WorkflowService_GetWorkflow_Call) Return(_a0 *domain.Workflow, _a1 error) *WorkflowService_GetWorkflow_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// ListWorkflows provides a mock function with given fields: ctx, page, limit
func (_m *WorkflowService) ListWorkflows(ctx context.Context, page int, limit int) ([]*domain.Workflow, int64, error) {
	ret := _m.Called(ctx, page, limit)

	var r0 []*domain.Workflow
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []*domain.Workflow); ok {
		r0 = rf(ctx, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Workflow)
		}
	}

	var r1 int64
	if rf, ok := ret.Get(1).(func(context.Context, int, int) int64); ok {
		r1 = rf(ctx, page, limit)
	} else {
		r1 = ret.Get(1).(int64)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context, int, int) error); ok {
		r2 = rf(ctx, page, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// WorkflowService_ListWorkflows_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListWorkflows'
type WorkflowService_ListWorkflows_Call struct {
	*mock.Call
}

// ListWorkflows is a helper method to define mock.On call
//  - ctx context.Context
//  - page int
//  - limit int
func (_e *WorkflowService_Expecter) ListWorkflows(ctx interface{}, page interface{}, limit interface{}) *WorkflowService_ListWorkflows_Call {
	return &WorkflowService_ListWorkflows_Call{Call: _e.mock.On("ListWorkflows", ctx, page, limit)}
}

func (_c *WorkflowService_ListWorkflows_Call) Run(run func(ctx context.Context, page int, limit int)) *WorkflowService_ListWorkflows_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *WorkflowService_ListWorkflows_Call) Return(_a0 []*domain.Workflow, _a1 int64, _a2 error) *WorkflowService_ListWorkflows_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

// UpdateWorkflow provides a mock function with given fields: ctx, id, name
func (_m *WorkflowService) UpdateWorkflow(ctx context.Context, id string, name string) (*domain.Workflow, error) {
	ret := _m.Called(ctx, id, name)

	var r0 *domain.Workflow
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *domain.Workflow); ok {
		r0 = rf(ctx, id, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Workflow)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, id, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WorkflowService_UpdateWorkflow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateWorkflow'
type WorkflowService_UpdateWorkflow_Call struct {
	*mock.Call
}

// UpdateWorkflow is a helper method to define mock.On call
//  - ctx context.Context
//  - id string
//  - name string
func (_e *WorkflowService_Expecter) UpdateWorkflow(ctx interface{}, id interface{}, name interface{}) *WorkflowService_UpdateWorkflow_Call {
	return &WorkflowService_UpdateWorkflow_Call{Call: _e.mock.On("UpdateWorkflow", ctx, id, name)}
}

func (_c *WorkflowService_UpdateWorkflow_Call) Run(run func(ctx context.Context, id string, name string)) *WorkflowService_UpdateWorkflow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *WorkflowService_UpdateWorkflow_Call) Return(_a0 *domain.Workflow, _a1 error) *WorkflowService_UpdateWorkflow_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

type mockConstructorTestingTNewWorkflowService interface {
	mock.TestingT
	Cleanup(func())
}

// NewWorkflowService creates a new instance of WorkflowService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewWorkflowService(t mockConstructorTestingTNewWorkflowService) *WorkflowService {
	mock := &WorkflowService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
