// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "workflow-approval/package/workflow/domain"

	mock "github.com/stretchr/testify/mock"
)

// WorkflowRepository is an autogenerated mock type for the WorkflowRepository type
type WorkflowRepository struct {
	mock.Mock
}

type WorkflowRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *WorkflowRepository) EXPECT() *WorkflowRepository_Expecter {
	return &WorkflowRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, workflow
func (_m *WorkflowRepository) Create(ctx context.Context, workflow *domain.Workflow) error {
	ret := _m.Called(ctx, workflow)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Workflow) error); ok {
		r0 = rf(ctx, workflow)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WorkflowRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type WorkflowRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//  - ctx context.Context
//  - workflow *domain.Workflow
func (_e *WorkflowRepository_Expecter) Create(ctx interface{}, workflow interface{}) *WorkflowRepository_Create_Call {
	return &WorkflowRepository_Create_Call{Call: _e.mock.On("Create", ctx, workflow)}
}

func (_c *WorkflowRepository_Create_Call) Run(run func(ctx context.Context, workflow *domain.Workflow)) *WorkflowRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Workflow))
	})
	return _c
}

func (_c *WorkflowRepository_Create_Call) Return(_a0 error) *WorkflowRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *WorkflowRepository) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WorkflowRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type WorkflowRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//  - ctx context.Context
//  - id string
func (_e *WorkflowRepository_Expecter) Delete(ctx interface{}, id interface{}) *WorkflowRepository_Delete_Call {
	return &WorkflowRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *WorkflowRepository_Delete_Call) Run(run func(ctx context.Context, id string)) *WorkflowRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *WorkflowRepository_Delete_Call) Return(_a0 error) *WorkflowRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *WorkflowRepository) GetByID(ctx context.Context, id string) (*domain.Workflow, error) {
	ret := _m.Called(ctx, id)

	var r0 *domain.Workflow
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Workflow); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Workflow)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WorkflowRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type WorkflowRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//  - ctx context.Context
//  - id string
func (_e *WorkflowRepository_Expecter) GetByID(ctx interface{}, id interface{}) *WorkflowRepository_GetByID_Call {
	return &WorkflowRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *WorkflowRepository_GetByID_Call) Run(run func(ctx context.Context, id string)) *WorkflowRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *WorkflowRepository_GetByID_Call) Return(_a0 *domain.Workflow, _a1 error) *WorkflowRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// List provides a mock function with given fields: ctx, page, limit
func (_m *WorkflowRepository) List(ctx context.Context, page int, limit int) ([]*domain.Workflow, int64, error) {
	ret := _m.Called(ctx, page, limit)

	var r0 []*domain.Workflow
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []*domain.Workflow); ok {
		r0 = rf(ctx, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Workflow)
		}
	}

	var r1 int64
	if rf, ok := ret.Get(1).(func(context.Context, int, int) int64); ok {
		r1 = rf(ctx, page, limit)
	} else {
		r1 = ret.Get(1).(int64)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context, int, int) error); ok {
		r2 = rf(ctx, page, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// WorkflowRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type WorkflowRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//  - ctx context.Context
//  - page int
//  - limit int
func (_e *WorkflowRepository_Expecter) List(ctx interface{}, page interface{}, limit interface{}) *WorkflowRepository_List_Call {
	return &WorkflowRepository_List_Call{Call: _e.mock.On("List", ctx, page, limit)}
}

func (_c *WorkflowRepository_List_Call) Run(run func(ctx context.Context, page int, limit int)) *WorkflowRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *WorkflowRepository_List_Call) Return(_a0 []*domain.Workflow, _a1 int64, _a2 error) *WorkflowRepository_List_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

// Update provides a mock function with given fields: ctx, workflow
func (_m *WorkflowRepository) Update(ctx context.Context, workflow *domain.Workflow) error {
	ret := _m.Called(ctx, workflow)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Workflow) error); ok {
		r0 = rf(ctx, workflow)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WorkflowRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type WorkflowRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//  - ctx context.Context
//  - workflow *domain.Workflow
func (_e *WorkflowRepository_Expecter) Update(ctx interface{}, workflow interface{}) *WorkflowRepository_Update_Call {
	return &WorkflowRepository_Update_Call{Call: _e.mock.On("Update", ctx, workflow)}
}

func (_c *WorkflowRepository_Update_Call) Run(run func(ctx context.Context, workflow *domain.Workflow)) *WorkflowRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Workflow))
	})
	return _c
}

func (_c *WorkflowRepository_Update_Call) Return(_a0 error) *WorkflowRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

type mockConstructorTestingTNewWorkflowRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewWorkflowRepository creates a new instance of WorkflowRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewWorkflowRepository(t mockConstructorTestingTNewWorkflowRepository) *WorkflowRepository {
	mock := &WorkflowRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
