// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "workflow-approval/package/approval_history/domain"
	dto "workflow-approval/package/approval_history/domain/dto"

	mock "github.com/stretchr/testify/mock"
)

// ApprovalHistoryService is an autogenerated mock type for the ApprovalHistoryService type
type ApprovalHistoryService struct {
	mock.Mock
}

type ApprovalHistoryService_Expecter struct {
	mock *mock.Mock
}

func (_m *ApprovalHistoryService) EXPECT() *ApprovalHistoryService_Expecter {
	return &ApprovalHistoryService_Expecter{mock: &_m.Mock}
}

// CreateApprovalHistory provides a mock function with given fields: ctx, requestID, workflowID, stepLevel, actorID, userID, action, comment
func (_m *ApprovalHistoryService) CreateApprovalHistory(ctx context.Context, requestID string, workflowID string, stepLevel int, actorID string, userID string, action domain.ApprovalAction, comment string) error {
	ret := _m.Called(ctx, requestID, workflowID, stepLevel, actorID, userID, action, comment)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int, string, string, domain.ApprovalAction, string) error); ok {
		r0 = rf(ctx, requestID, workflowID, stepLevel, actorID, userID, action, comment)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ApprovalHistoryService_CreateApprovalHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateApprovalHistory'
type ApprovalHistoryService_CreateApprovalHistory_Call struct {
	*mock.Call
}

// CreateApprovalHistory is a helper method to define mock.On call
//  - ctx context.Context
//  - requestID string
//  - workflowID string
//  - stepLevel int
//  - actorID string
//  - userID string
//  - action domain.ApprovalAction
//  - comment string
func (_e *ApprovalHistoryService_Expecter) CreateApprovalHistory(ctx interface{}, requestID interface{}, workflowID interface{}, stepLevel interface{}, actorID interface{}, userID interface{}, action interface{}, comment interface{}) *ApprovalHistoryService_CreateApprovalHistory_Call {
	return &ApprovalHistoryService_CreateApprovalHistory_Call{Call: _e.mock.On("CreateApprovalHistory", ctx, requestID, workflowID, stepLevel, actorID, userID, action, comment)}
}

func (_c *ApprovalHistoryService_CreateApprovalHistory_Call) Run(run func(ctx context.Context, requestID string, workflowID string, stepLevel int, actorID string, userID string, action domain.ApprovalAction, comment string)) *ApprovalHistoryService_CreateApprovalHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(int), args[4].(string), args[5].(string), args[6].(domain.ApprovalAction), args[7].(string))
	})
	return _c
}

func (_c *ApprovalHistoryService_CreateApprovalHistory_Call) Return(_a0 error) *ApprovalHistoryService_CreateApprovalHistory_Call {
	_c.Call.Return(_a0)
	return _c
}

// GetHistoryByRequestID provides a mock function with given fields: ctx, requestID
func (_m *ApprovalHistoryService) GetHistoryByRequestID(ctx context.Context, requestID string) ([]*dto.ApprovalHistoryResponse, error) {
	ret := _m.Called(ctx, requestID)

	var r0 []*dto.ApprovalHistoryResponse
	if rf, ok := ret.Get(0).(func(context.Context, string) []*dto.ApprovalHistoryResponse); ok {
		r0 = rf(ctx, requestID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*dto.ApprovalHistoryResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, requestID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ApprovalHistoryService_GetHistoryByRequestID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHistoryByRequestID'
type ApprovalHistoryService_GetHistoryByRequestID_Call struct {
	*mock.Call
}

// GetHistoryByRequestID is a helper method to define mock.On call
//  - ctx context.Context
//  - requestID string
func (_e *ApprovalHistoryService_Expecter) GetHistoryByRequestID(ctx interface{}, requestID interface{}) *ApprovalHistoryService_GetHistoryByRequestID_Call {
	return &ApprovalHistoryService_GetHistoryByRequestID_Call{Call: _e.mock.On("GetHistoryByRequestID", ctx, requestID)}
}

func (_c *ApprovalHistoryService_GetHistoryByRequestID_Call) Run(run func(ctx context.Context, requestID string)) *ApprovalHistoryService_GetHistoryByRequestID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ApprovalHistoryService_GetHistoryByRequestID_Call) Return(_a0 []*dto.ApprovalHistoryResponse, _a1 error) *ApprovalHistoryService_GetHistoryByRequestID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

type mockConstructorTestingTNewApprovalHistoryService interface {
	mock.TestingT
	Cleanup(func())
}

// NewApprovalHistoryService creates a new instance of ApprovalHistoryService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewApprovalHistoryService(t mockConstructorTestingTNewApprovalHistoryService) *ApprovalHistoryService {
	mock := &ApprovalHistoryService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
