// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "workflow-approval/package/approval_history/domain"

	mock "github.com/stretchr/testify/mock"
)

// ApprovalHistoryRepository is an autogenerated mock type for the ApprovalHistoryRepository type
type ApprovalHistoryRepository struct {
	mock.Mock
}

type ApprovalHistoryRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *ApprovalHistoryRepository) EXPECT() *ApprovalHistoryRepository_Expecter {
	return &ApprovalHistoryRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, history
func (_m *ApprovalHistoryRepository) Create(ctx context.Context, history *domain.ApprovalHistory) error {
	ret := _m.Called(ctx, history)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.ApprovalHistory) error); ok {
		r0 = rf(ctx, history)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ApprovalHistoryRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type ApprovalHistoryRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//  - ctx context.Context
//  - history *domain.ApprovalHistory
func (_e *ApprovalHistoryRepository_Expecter) Create(ctx interface{}, history interface{}) *ApprovalHistoryRepository_Create_Call {
	return &ApprovalHistoryRepository_Create_Call{Call: _e.mock.On("Create", ctx, history)}
}

func (_c *ApprovalHistoryRepository_Create_Call) Run(run func(ctx context.Context, history *domain.ApprovalHistory)) *ApprovalHistoryRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.ApprovalHistory))
	})
	return _c
}

func (_c *ApprovalHistoryRepository_Create_Call) Return(_a0 error) *ApprovalHistoryRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

// GetByActorID provides a mock function with given fields: ctx, actorID
func (_m *ApprovalHistoryRepository) GetByActorID(ctx context.Context, actorID string) ([]*domain.ApprovalHistory, error) {
	ret := _m.Called(ctx, actorID)

	var r0 []*domain.ApprovalHistory
	if rf, ok := ret.Get(0).(func(context.Context, string) []*domain.ApprovalHistory); ok {
		r0 = rf(ctx, actorID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.ApprovalHistory)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, actorID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ApprovalHistoryRepository_GetByActorID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByActorID'
type ApprovalHistoryRepository_GetByActorID_Call struct {
	*mock.Call
}

// GetByActorID is a helper method to define mock.On call
//  - ctx context.Context
//  - actorID string
func (_e *ApprovalHistoryRepository_Expecter) GetByActorID(ctx interface{}, actorID interface{}) *ApprovalHistoryRepository_GetByActorID_Call {
	return &ApprovalHistoryRepository_GetByActorID_Call{Call: _e.mock.On("GetByActorID", ctx, actorID)}
}

func (_c *ApprovalHistoryRepository_GetByActorID_Call) Run(run func(ctx context.Context, actorID string)) *ApprovalHistoryRepository_GetByActorID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ApprovalHistoryRepository_GetByActorID_Call) Return(_a0 []*domain.ApprovalHistory, _a1 error) *ApprovalHistoryRepository_GetByActorID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *ApprovalHistoryRepository) GetByID(ctx context.Context, id string) (*domain.ApprovalHistory, error) {
	ret := _m.Called(ctx, id)

	var r0 *domain.ApprovalHistory
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.ApprovalHistory); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ApprovalHistory)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ApprovalHistoryRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type ApprovalHistoryRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//  - ctx context.Context
//  - id string
func (_e *ApprovalHistoryRepository_Expecter) GetByID(ctx interface{}, id interface{}) *ApprovalHistoryRepository_GetByID_Call {
	return &ApprovalHistoryRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *ApprovalHistoryRepository_GetByID_Call) Run(run func(ctx context.Context, id string)) *ApprovalHistoryRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ApprovalHistoryRepository_GetByID_Call) Return(_a0 *domain.ApprovalHistory, _a1 error) *ApprovalHistoryRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// GetByRequestID provides a mock function with given fields: ctx, requestID
func (_m *ApprovalHistoryRepository) GetByRequestID(ctx context.Context, requestID string) ([]*domain.ApprovalHistory, error) {
	ret := _m.Called(ctx, requestID)

	var r0 []*domain.ApprovalHistory
	if rf, ok := ret.Get(0).(func(context.Context, string) []*domain.ApprovalHistory); ok {
		r0 = rf(ctx, requestID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.ApprovalHistory)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, requestID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ApprovalHistoryRepository_GetByRequestID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByRequestID'
type ApprovalHistoryRepository_GetByRequestID_Call struct {
	*mock.Call
}

// GetByRequestID is a helper method to define mock.On call
//  - ctx context.Context
//  - requestID string
func (_e *ApprovalHistoryRepository_Expecter) GetByRequestID(ctx interface{}, requestID interface{}) *ApprovalHistoryRepository_GetByRequestID_Call {
	return &ApprovalHistoryRepository_GetByRequestID_Call{Call: _e.mock.On("GetByRequestID", ctx, requestID)}
}

func (_c *ApprovalHistoryRepository_GetByRequestID_Call) Run(run func(ctx context.Context, requestID string)) *ApprovalHistoryRepository_GetByRequestID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ApprovalHistoryRepository_GetByRequestID_Call) Return(_a0 []*domain.ApprovalHistory, _a1 error) *ApprovalHistoryRepository_GetByRequestID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// GetByRequestIDOrdered provides a mock function with given fields: ctx, requestID
func (_m *ApprovalHistoryRepository) GetByRequestIDOrdered(ctx context.Context, requestID string) ([]*domain.ApprovalHistory, error) {
	ret := _m.Called(ctx, requestID)

	var r0 []*domain.ApprovalHistory
	if rf, ok := ret.Get(0).(func(context.Context, string) []*domain.ApprovalHistory); ok {
		r0 = rf(ctx, requestID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.ApprovalHistory)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, requestID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ApprovalHistoryRepository_GetByRequestIDOrdered_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByRequestIDOrdered'
type ApprovalHistoryRepository_GetByRequestIDOrdered_Call struct {
	*mock.Call
}

// GetByRequestIDOrdered is a helper method to define mock.On call
//  - ctx context.Context
//  - requestID string
func (_e *ApprovalHistoryRepository_Expecter) GetByRequestIDOrdered(ctx interface{}, requestID interface{}) *ApprovalHistoryRepository_GetByRequestIDOrdered_Call {
	return &ApprovalHistoryRepository_GetByRequestIDOrdered_Call{Call: _e.mock.On("GetByRequestIDOrdered", ctx, requestID)}
}

func (_c *ApprovalHistoryRepository_GetByRequestIDOrdered_Call) Run(run func(ctx context.Context, requestID string)) *ApprovalHistoryRepository_GetByRequestIDOrdered_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *ApprovalHistoryRepository_GetByRequestIDOrdered_Call) Return(_a0 []*domain.ApprovalHistory, _a1 error) *ApprovalHistoryRepository_GetByRequestIDOrdered_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

type mockConstructorTestingTNewApprovalHistoryRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewApprovalHistoryRepository creates a new instance of ApprovalHistoryRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewApprovalHistoryRepository(t mockConstructorTestingTNewApprovalHistoryRepository) *ApprovalHistoryRepository {
	mock := &ApprovalHistoryRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
