// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "workflow-approval/package/request/domain"

	mock "github.com/stretchr/testify/mock"
)

// RequestRepository is an autogenerated mock type for the RequestRepository type
type RequestRepository struct {
	mock.Mock
}

type RequestRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *RequestRepository) EXPECT() *RequestRepository_Expecter {
	return &RequestRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, request
func (_m *RequestRepository) Create(ctx context.Context, request *domain.Request) error {
	ret := _m.Called(ctx, request)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Request) error); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RequestRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type RequestRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//  - ctx context.Context
//  - request *domain.Request
func (_e *RequestRepository_Expecter) Create(ctx interface{}, request interface{}) *RequestRepository_Create_Call {
	return &RequestRepository_Create_Call{Call: _e.mock.On("Create", ctx, request)}
}

func (_c *RequestRepository_Create_Call) Run(run func(ctx context.Context, request *domain.Request)) *RequestRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Request))
	})
	return _c
}

func (_c *RequestRepository_Create_Call) Return(_a0 error) *RequestRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *RequestRepository) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RequestRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type RequestRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//  - ctx context.Context
//  - id string
func (_e *RequestRepository_Expecter) Delete(ctx interface{}, id interface{}) *RequestRepository_Delete_Call {
	return &RequestRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *RequestRepository_Delete_Call) Run(run func(ctx context.Context, id string)) *RequestRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *RequestRepository_Delete_Call) Return(_a0 error) *RequestRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *RequestRepository) GetByID(ctx context.Context, id string) (*domain.Request, error) {
	ret := _m.Called(ctx, id)

	var r0 *domain.Request
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Request); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Request)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RequestRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type RequestRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//  - ctx context.Context
//  - id string
func (_e *RequestRepository_Expecter) GetByID(ctx interface{}, id interface{}) *RequestRepository_GetByID_Call {
	return &RequestRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *RequestRepository_GetByID_Call) Run(run func(ctx context.Context, id string)) *RequestRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *RequestRepository_GetByID_Call) Return(_a0 *domain.Request, _a1 error) *RequestRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// GetByIDForUpdate provides a mock function with given fields: ctx, id
func (_m *RequestRepository) GetByIDForUpdate(ctx context.Context, id string) (*domain.Request, error) {
	ret := _m.Called(ctx, id)

	var r0 *domain.Request
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Request); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Request)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RequestRepository_GetByIDForUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByIDForUpdate'
type RequestRepository_GetByIDForUpdate_Call struct {
	*mock.Call
}

// GetByIDForUpdate is a helper method to define mock.On call
//  - ctx context.Context
//  - id string
func (_e *RequestRepository_Expecter) GetByIDForUpdate(ctx interface{}, id interface{}) *RequestRepository_GetByIDForUpdate_Call {
	return &RequestRepository_GetByIDForUpdate_Call{Call: _e.mock.On("GetByIDForUpdate", ctx, id)}
}

func (_c *RequestRepository_GetByIDForUpdate_Call) Run(run func(ctx context.Context, id string)) *RequestRepository_GetByIDForUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *RequestRepository_GetByIDForUpdate_Call) Return(_a0 *domain.Request, _a1 error) *RequestRepository_GetByIDForUpdate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// List provides a mock function with given fields: ctx, page, limit, status
func (_m *RequestRepository) List(ctx context.Context, page int, limit int, status *domain.RequestStatus) ([]*domain.Request, int64, error) {
	ret := _m.Called(ctx, page, limit, status)

	var r0 []*domain.Request
	if rf, ok := ret.Get(0).(func(context.Context, int, int, *domain.RequestStatus) []*domain.Request); ok {
		r0 = rf(ctx, page, limit, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Request)
		}
	}

	var r1 int64
	if rf, ok := ret.Get(1).(func(context.Context, int, int, *domain.RequestStatus) int64); ok {
		r1 = rf(ctx, page, limit, status)
	} else {
		r1 = ret.Get(1).(int64)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context, int, int, *domain.RequestStatus) error); ok {
		r2 = rf(ctx, page, limit, status)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// RequestRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type RequestRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//  - ctx context.Context
//  - page int
//  - limit int
//  - status *domain.RequestStatus
func (_e *RequestRepository_Expecter) List(ctx interface{}, page interface{}, limit interface{}, status interface{}) *RequestRepository_List_Call {
	return &RequestRepository_List_Call{Call: _e.mock.On("List", ctx, page, limit, status)}
}

func (_c *RequestRepository_List_Call) Run(run func(ctx context.Context, page int, limit int, status *domain.RequestStatus)) *RequestRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int), args[3].(*domain.RequestStatus))
	})
	return _c
}

func (_c *RequestRepository_List_Call) Return(_a0 []*domain.Request, _a1 int64, _a2 error) *RequestRepository_List_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

// Update provides a mock function with given fields: ctx, request
func (_m *RequestRepository) Update(ctx context.Context, request *domain.Request) error {
	ret := _m.Called(ctx, request)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Request) error); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RequestRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type RequestRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//  - ctx context.Context
//  - request *domain.Request
func (_e *RequestRepository_Expecter) Update(ctx interface{}, request interface{}) *RequestRepository_Update_Call {
	return &RequestRepository_Update_Call{Call: _e.mock.On("Update", ctx, request)}
}

func (_c *RequestRepository_Update_Call) Run(run func(ctx context.Context, request *domain.Request)) *RequestRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Request))
	})
	return _c
}

func (_c *RequestRepository_Update_Call) Return(_a0 error) *RequestRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

type mockConstructorTestingTNewRequestRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewRequestRepository creates a new instance of RequestRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRequestRepository(t mockConstructorTestingTNewRequestRepository) *RequestRepository {
	mock := &RequestRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
