// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "workflow-approval/package/request/domain"

	mock "github.com/stretchr/testify/mock"
)

// RequestService is an autogenerated mock type for the RequestService type
type RequestService struct {
	mock.Mock
}

type RequestService_Expecter struct {
	mock *mock.Mock
}

func (_m *RequestService) EXPECT() *RequestService_Expecter {
	return &RequestService_Expecter{mock: &_m.Mock}
}

// Approve provides a mock function with given fields: ctx, requestID, userID, actorID, isAdmin
func (_m *RequestService) Approve(ctx context.Context, requestID string, userID string, actorID string, isAdmin bool) (*domain.Request, error) {
	ret := _m.Called(ctx, requestID, userID, actorID, isAdmin)

	var r0 *domain.Request
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, bool) *domain.Request); ok {
		r0 = rf(ctx, requestID, userID, actorID, isAdmin)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Request)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, bool) error); ok {
		r1 = rf(ctx, requestID, userID, actorID, isAdmin)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RequestService_Approve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Approve'
type RequestService_Approve_Call struct {
	*mock.Call
}

// Approve is a helper method to define mock.On call
//  - ctx context.Context
//  - requestID string
//  - userID string
//  - actorID string
//  - isAdmin bool
func (_e *RequestService_Expecter) Approve(ctx interface{}, requestID interface{}, userID interface{}, actorID interface{}, isAdmin interface{}) *RequestService_Approve_Call {
	return &RequestService_Approve_Call{Call: _e.mock.On("Approve", ctx, requestID, userID, actorID, isAdmin)}
}

func (_c *RequestService_Approve_Call) Run(run func(ctx context.Context, requestID string, userID string, actorID string, isAdmin bool)) *RequestService_Approve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(bool))
	})
	return _c
}

func (_c *RequestService_Approve_Call) Return(_a0 *domain.Request, _a1 error) *RequestService_Approve_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// CreateRequest provides a mock function with given fields: ctx, workflowID, requesterID, amount, title, description
func (_m *RequestService) CreateRequest(ctx context.Context, workflowID string, requesterID string, amount float64, title string, description string) (*domain.Request, error) {
	ret := _m.Called(ctx, workflowID, requesterID, amount, title, description)

	var r0 *domain.Request
	if rf, ok := ret.Get(0).(func(context.Context, string, string, float64, string, string) *domain.Request); ok {
		r0 = rf(ctx, workflowID, requesterID, amount, title, description)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Request)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string, float64, string, string) error); ok {
		r1 = rf(ctx, workflowID, requesterID, amount, title, description)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RequestService_CreateRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRequest'
type RequestService_CreateRequest_Call struct {
	*mock.Call
}

// CreateRequest is a helper method to define mock.On call
//  - ctx context.Context
//  - workflowID string
//  - requesterID string
//  - amount float64
//  - title string
//  - description string
func (_e *RequestService_Expecter) CreateRequest(ctx interface{}, workflowID interface{}, requesterID interface{}, amount interface{}, title interface{}, description interface{}) *RequestService_CreateRequest_Call {
	return &RequestService_CreateRequest_Call{Call: _e.mock.On("CreateRequest", ctx, workflowID, requesterID, amount, title, description)}
}

func (_c *RequestService_CreateRequest_Call) Run(run func(ctx context.Context, workflowID string, requesterID string, amount float64, title string, description string)) *RequestService_CreateRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(float64), args[4].(string), args[5].(string))
	})
	return _c
}

func (_c *RequestService_CreateRequest_Call) Return(_a0 *domain.Request, _a1 error) *RequestService_CreateRequest_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// DeleteRequest provides a mock function with given fields: ctx, id
func (_m *RequestService) DeleteRequest(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RequestService_DeleteRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRequest'
type RequestService_DeleteRequest_Call struct {
	*mock.Call
}

// DeleteRequest is a helper method to define mock.On call
//  - ctx context.Context
//  - id string
func (_e *RequestService_Expecter) DeleteRequest(ctx interface{}, id interface{}) *RequestService_DeleteRequest_Call {
	return &RequestService_DeleteRequest_Call{Call: _e.mock.On("DeleteRequest", ctx, id)}
}

func (_c *RequestService_DeleteRequest_Call) Run(run func(ctx context.Context, id string)) *RequestService_DeleteRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *RequestService_DeleteRequest_Call) Return(_a0 error) *RequestService_DeleteRequest_Call {
	_c.Call.Return(_a0)
	return _c
}

// GetRequest provides a mock function with given fields: ctx, id
func (_m *RequestService) GetRequest(ctx context.Context, id string) (*domain.Request, error) {
	ret := _m.Called(ctx, id)

	var r0 *domain.Request
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Request); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Request)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RequestService_GetRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRequest'
type RequestService_GetRequest_Call struct {
	*mock.Call
}

// GetRequest is a helper method to define mock.On call
//  - ctx context.Context
//  - id string
func (_e *RequestService_Expecter) GetRequest(ctx interface{}, id interface{}) *RequestService_GetRequest_Call {
	return &RequestService_GetRequest_Call{Call: _e.mock.On("GetRequest", ctx, id)}
}

func (_c *RequestService_GetRequest_Call) Run(run func(ctx context.Context, id string)) *RequestService_GetRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *RequestService_GetRequest_Call) Return(_a0 *domain.Request, _a1 error) *RequestService_GetRequest_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// ListRequests provides a mock function with given fields: ctx, page, limit, status
func (_m *RequestService) ListRequests(ctx context.Context, page int, limit int, status *domain.RequestStatus) ([]*domain.Request, int64, error) {
	ret := _m.Called(ctx, page, limit, status)

	var r0 []*domain.Request
	if rf, ok := ret.Get(0).(func(context.Context, int, int, *domain.RequestStatus) []*domain.Request); ok {
		r0 = rf(ctx, page, limit, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Request)
		}
	}

	var r1 int64
	if rf, ok := ret.Get(1).(func(context.Context, int, int, *domain.RequestStatus) int64); ok {
		r1 = rf(ctx, page, limit, status)
	} else {
		r1 = ret.Get(1).(int64)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context, int, int, *domain.RequestStatus) error); ok {
		r2 = rf(ctx, page, limit, status)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// RequestService_ListRequests_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListRequests'
type RequestService_ListRequests_Call struct {
	*mock.Call
}

// ListRequests is a helper method to define mock.On call
//  - ctx context.Context
//  - page int
//  - limit int
//  - status *domain.RequestStatus
func (_e *RequestService_Expecter) ListRequests(ctx interface{}, page interface{}, limit interface{}, status interface{}) *RequestService_ListRequests_Call {
	return &RequestService_ListRequests_Call{Call: _e.mock.On("ListRequests", ctx, page, limit, status)}
}

func (_c *RequestService_ListRequests_Call) Run(run func(ctx context.Context, page int, limit int, status *domain.RequestStatus)) *RequestService_ListRequests_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int), args[3].(*domain.RequestStatus))
	})
	return _c
}

func (_c *RequestService_ListRequests_Call) Return(_a0 []*domain.Request, _a1 int64, _a2 error) *RequestService_ListRequests_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

// LockRequest provides a mock function with given fields: requestID
func (_m *RequestService) LockRequest(requestID string) func() {
	ret := _m.Called(requestID)

	var r0 func()
	if rf, ok := ret.Get(0).(func(string) func()); ok {
		r0 = rf(requestID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(func())
		}
	}

	return r0
}

// RequestService_LockRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LockRequest'
type RequestService_LockRequest_Call struct {
	*mock.Call
}

// LockRequest is a helper method to define mock.On call
//  - requestID string
func (_e *RequestService_Expecter) LockRequest(requestID interface{}) *RequestService_LockRequest_Call {
	return &RequestService_LockRequest_Call{Call: _e.mock.On("LockRequest", requestID)}
}

func (_c *RequestService_LockRequest_Call) Run(run func(requestID string)) *RequestService_LockRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *RequestService_LockRequest_Call) Return(_a0 func()) *RequestService_LockRequest_Call {
	_c.Call.Return(_a0)
	return _c
}

// Reject provides a mock function with given fields: ctx, requestID, userID, actorID, isAdmin, reason
func (_m *RequestService) Reject(ctx context.Context, requestID string, userID string, actorID string, isAdmin bool, reason string) (*domain.Request, error) {
	ret := _m.Called(ctx, requestID, userID, actorID, isAdmin, reason)

	var r0 *domain.Request
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, bool, string) *domain.Request); ok {
		r0 = rf(ctx, requestID, userID, actorID, isAdmin, reason)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Request)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, bool, string) error); ok {
		r1 = rf(ctx, requestID, userID, actorID, isAdmin, reason)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RequestService_Reject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reject'
type RequestService_Reject_Call struct {
	*mock.Call
}

// Reject is a helper method to define mock.On call
//  - ctx context.Context
//  - requestID string
//  - userID string
//  - actorID string
//  - isAdmin bool
//  - reason string
func (_e *RequestService_Expecter) Reject(ctx interface{}, requestID interface{}, userID interface{}, actorID interface{}, isAdmin interface{}, reason interface{}) *RequestService_Reject_Call {
	return &RequestService_Reject_Call{Call: _e.mock.On("Reject", ctx, requestID, userID, actorID, isAdmin, reason)}
}

func (_c *RequestService_Reject_Call) Run(run func(ctx context.Context, requestID string, userID string, actorID string, isAdmin bool, reason string)) *RequestService_Reject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(bool), args[5].(string))
	})
	return _c
}

func (_c *RequestService_Reject_Call) Return(_a0 *domain.Request, _a1 error) *RequestService_Reject_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// UpdateRequest provides a mock function with given fields: ctx, id, amount, title, description
func (_m *RequestService) UpdateRequest(ctx context.Context, id string, amount float64, title string, description string) (*domain.Request, error) {
	ret := _m.Called(ctx, id, amount, title, description)

	var r0 *domain.Request
	if rf, ok := ret.Get(0).(func(context.Context, string, float64, string, string) *domain.Request); ok {
		r0 = rf(ctx, id, amount, title, description)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Request)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, float64, string, string) error); ok {
		r1 = rf(ctx, id, amount, title, description)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RequestService_UpdateRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRequest'
type RequestService_UpdateRequest_Call struct {
	*mock.Call
}

// UpdateRequest is a helper method to define mock.On call
//  - ctx context.Context
//  - id string
//  - amount float64
//  - title string
//  - description string
func (_e *RequestService_Expecter) UpdateRequest(ctx interface{}, id interface{}, amount interface{}, title interface{}, description interface{}) *RequestService_UpdateRequest_Call {
	return &RequestService_UpdateRequest_Call{Call: _e.mock.On("UpdateRequest", ctx, id, amount, title, description)}
}

func (_c *RequestService_UpdateRequest_Call) Run(run func(ctx context.Context, id string, amount float64, title string, description string)) *RequestService_UpdateRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(float64), args[3].(string), args[4].(string))
	})
	return _c
}

func (_c *RequestService_UpdateRequest_Call) Return(_a0 *domain.Request, _a1 error) *RequestService_UpdateRequest_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

type mockConstructorTestingTNewRequestService interface {
	mock.TestingT
	Cleanup(func())
}

// NewRequestService creates a new instance of RequestService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRequestService(t mockConstructorTestingTNewRequestService) *RequestService {
	mock := &RequestService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
